/*
 * DIO_cnfg.c
 *
 *  Created on: Sep 22, 2019
 *      Author: HOBA
 */


#include "DIO_cnfg.h"



DIO_cnfg_t DIO_cnfg_arr[NUM_OF_PINS] =
{
	
	// initialize the Keypad Pins
	{KEYPAD_PORT_,PIN2,OUTPUT,HIGH,NA,INITIALIZED},
	{KEYPAD_PORT_,PIN3,OUTPUT,HIGH,NA,INITIALIZED},
	{KEYPAD_PORT_,PIN4,OUTPUT,HIGH,NA,INITIALIZED},
	{KEYPAD_PORT_,PIN5,INPUT,NA,PULLUP,INITIALIZED},
	{KEYPAD_PORT_,PIN6,INPUT,NA,PULLUP,INITIALIZED},
	{KEYPAD_PORT_,PIN7,INPUT,NA,PULLUP,INITIALIZED},
	
	// initialize the LCD Pins
	{LCD_4Bits_PORT_,PIN1,OUTPUT,NA,NA,INITIALIZED},
	{LCD_4Bits_PORT_,PIN2,OUTPUT,NA,NA,INITIALIZED},
	{LCD_4Bits_PORT_,PIN3,OUTPUT,NA,NA,INITIALIZED},
	{LCD_4Bits_PORT_,PIN4,OUTPUT,NA,NA,INITIALIZED},
	{LCD_4Bits_PORT_,PIN5,OUTPUT,NA,NA,INITIALIZED},
	{LCD_4Bits_PORT_,PIN6,OUTPUT,NA,NA,INITIALIZED},
	{LCD_4Bits_PORT_,PIN7,OUTPUT,NA,NA,INITIALIZED}
			
		
	
	/*
	// initialize the Keypad Pins
	{PORT_C,PIN2,INPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN3,INPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN4,INPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN5,OUTPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN6,OUTPUT,NA,PULLUP,INITIALIZED},
	{PORT_C,PIN7,OUTPUT,NA,PULLUP,INITIALIZED}
	*/
	
	/*
		{PORT_D,PIN4,INPUT,NA,PULLUP,INITIALIZED},
		{PORT_D,PIN2,INPUT,NA,PULLUP,INITIALIZED}
	*/
};

